// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfeHuDsC9vdDrUFPoGPb9UOX6rcIh0sAw',
    appId: '1:1022758642462:web:f47b8c8738df44c48c5f0f',
    messagingSenderId: '1022758642462',
    projectId: 'tripchain-bb698',
    authDomain: 'tripchain-bb698.firebaseapp.com',
    storageBucket: 'tripchain-bb698.firebasestorage.app',
    measurementId: 'G-1QNQP5MCG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoFQ0TAhYngZYztqKIFW9Pi2wqdISre1s',
    appId: '1:1022758642462:android:57a1290fafde1d3c8c5f0f',
    messagingSenderId: '1022758642462',
    projectId: 'tripchain-bb698',
    storageBucket: 'tripchain-bb698.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuR82d12MlX92pyH1Jy8sESe8_tUMajUg',
    appId: '1:1022758642462:ios:79438f36d5ce20bf8c5f0f',
    messagingSenderId: '1022758642462',
    projectId: 'tripchain-bb698',
    storageBucket: 'tripchain-bb698.firebasestorage.app',
    iosBundleId: 'com.example.tripChain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfeHuDsC9vdDrUFPoGPb9UOX6rcIh0sAw',
    appId: '1:1022758642462:web:ec00f84c2eeee45f8c5f0f',
    messagingSenderId: '1022758642462',
    projectId: 'tripchain-bb698',
    authDomain: 'tripchain-bb698.firebaseapp.com',
    storageBucket: 'tripchain-bb698.firebasestorage.app',
    measurementId: 'G-T2D9TJVH0S',
  );
}
